### ISSUE TITLE
trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by nickylee11** [CarGuo/GSYRecordWave#41]
运行时依然会出现崩溃的情况。日志如下：
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@26696e14
                                                                                              at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
                                                                                              at android.graphics.Canvas.drawBitmap(Canvas.java:1280)
                                                                                              at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:253)

**Comment by CarGuo** [comment]
demo中怎么复现

**Comment by Robin-Gao** [comment]
我也遇到了这种情况

**Comment by CarGuo** [comment]
这种情况一般出现在界面销毁了，但是绘制线程还在跑的情况
