### ISSUE TITLE
在8.1的系统上无法录音,java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by tempersitu** [CarGuo/GSYRecordWave#46]
在录音的过程中一直出现
 W/System.err:     at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at com.shuyu.waveview.AudioWaveView.deepCopy(AudioWaveView.java:296)
        at com.shuyu.waveview.AudioWaveView$drawThread.run(AudioWaveView.java:209).
然后点停止,再点播放就崩溃了.
java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at com.shuyu.waveview.AudioPlayer$1.run(AudioPlayer.java:90)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by CarGuo** [comment]
demo中复现？机型是？

**Comment by tempersitu** [comment]
@CarGuo 原来有录到音的.有mp3文件在,但是一直报warning.而且点播放是会崩溃.是在demo中复现的.Nexus 6P, 原生8.1系统. 而且不是每次都会,有时是"波形播放"会崩溃,点"波形播放"崩溃的时候是背景还在播的,但出了崩溃的弹窗.
java.lang.IllegalStateException
at android.media.MediaPlayer.isPlaying(Native Method)
at com.shuyu.waveview.AudioPlayer$1.run(AudioPlayer.java:90)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
