### ISSUE TITLE
error ： dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

### ISSUE THREAD

**Issue by xue12311** [CarGuo/GSYRecordWave#62]
手机 ：小米手机 Android 9
有时会出现报错：dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
具体日志：
  java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.czt.mp3recorder.util.LameUtil.<clinit>(LameUtil.java:8)
        at com.czt.mp3recorder.util.LameUtil.init(Native Method)
        at com.czt.mp3recorder.MP3Recorder.initAudioRecorder(MP3Recorder.java:230)
        at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:94)
       
有时出现，但是重新打开APP又可以了

**Comment by xue12311** [comment]
> 手机 ：小米手机 Android 9
> 有时会出现报错：dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
> 具体日志：
> java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libmp3lame.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> at java.lang.System.loadLibrary(System.java:1669)
> at com.czt.mp3recorder.util.LameUtil.(LameUtil.java:8)
> at com.czt.mp3recorder.util.LameUtil.init(Native Method)
> at com.czt.mp3recorder.MP3Recorder.initAudioRecorder(MP3Recorder.java:230)
> at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:94)
> 
> 有时出现，但是重新打开APP又可以了
